#!/usr/bin/env python3
"""Generate engine/gen/jacktables.gen.{hpp,cpp} from the Droid Forge's
droidfirmware.json (vendored via tools/droidcheck). Deterministic output;
generated files are committed. Rerun with `make gen` after a Forge update."""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "tools/droidcheck/vendor/droidforge/droidforge/droidfirmware.json"
OUT = ROOT / "engine/gen"

TYPE_MAP = {"cv": "Cv", "gate": "Gate", "trigger": "Trigger",
            "fraction": "Fraction", "bipolar": "Bipolar", "integer": "Integer",
            "stepped": "Stepped", "voltperoctave": "VoltPerOctave", "text": "Text"}
HINT_MAP = {"input": "Input", "output": "Output", "taptempo_input": "TaptempoInput",
            "trigger_input": "TriggerInput", "trigger_output": "TriggerOutput"}


def parse_default(s):
    """Parse a JSON default string into (hasDefault, value)."""
    if s is None:
        return False, 0.0
    s = s.strip()
    if s == "on":
        return True, 1.0
    if s == "off":
        return True, 0.0
    # "unpatched" means the jack has no meaningful default value (very common
    # across text/select/header/preset-type jacks in the firmware JSON) —
    # extended beyond the brief's regex set, treated like `None`.
    if s == "unpatched":
        return False, 0.0
    m = re.fullmatch(r"\$\\frac\{(-?\d+)\}\{(\d+)\}\$(V?)", s)   # e.g. $\frac{1}{6}$V
    if m:
        v = int(m.group(1)) / int(m.group(2))
        if m.group(3):
            v /= 10
        return True, v
    m = re.fullmatch(r"(-?\d+(?:\.\d+)?)(V|%)?", s)
    if m:
        v = float(m.group(1))
        if m.group(2) == "V":
            v /= 10
        elif m.group(2) == "%":
            v /= 100
        return True, v
    raise ValueError(f"unparsable default: {s!r}")


def base_name(j):
    """Base name of a jack; array element k is base + k (1-based).
    For arrays the firmware supplies an explicit "prefix" — use it, because
    stripping trailing digits off the first element name is WRONG when the
    base itself ends in a digit (matrixmixer/fadermatrix expose button11 …
    button44 and led11 … led44, whose real bases are button1 … button4 /
    led1 … led4, not "button"/"led"). Fall back to the strip-digits heuristic
    only for the rare array without a prefix. Scalars keep their literal name.
    Some firmware entries list array jacks comma-separated ('input1,
    input2'), which leaves a trailing comma on the first token."""
    if j.get("count"):
        if j.get("prefix"):
            return j["prefix"]
        first = j["name"].split()[0].rstrip(",")
        return re.sub(r"\d+$", "", first)
    return j["name"].split()[0].rstrip(",")


def emit_jack(j, is_input):
    has_def, dv = parse_default(j.get("default"))
    t = TYPE_MAP[j["type"]]
    h = HINT_MAP[j["ramhint"]]
    short = j.get("short") or ""
    return (f'    {{"{base_name(j)}", "{short}", JackType::{t}, RamHint::{h}, '
            f'{j.get("count", 1)}, {j.get("start_at", 1)}, '
            f'{"true" if is_input else "false"}, '
            f'{"true" if has_def else "false"}, {dv!r}f}},')


def main():
    if not SRC.exists():
        sys.exit(f"missing {SRC}\nRun tools/droidcheck/build.sh first to clone the Forge.")
    fw = json.loads(SRC.read_text())
    circuits = sorted(fw["circuits"].items())
    assert len(circuits) == 76, f"expected 76 circuits, got {len(circuits)}"

    cpp = ['// GENERATED by tools/jackgen/jackgen.py — DO NOT EDIT',
           f'// source firmware: {fw["firmware_version"]}',
           '#include "jacktables.gen.hpp"',
           '#include <cstring>', '#include <cctype>', '', 'namespace droid::gen {', '']
    hpp_names = []
    for name, c in circuits:
        cpp.append(f'static const JackDef kJacks_{name}[] = {{')
        n = 0
        for j in c["inputs"]:
            cpp.append(emit_jack(j, True)); n += 1
        for j in c["outputs"]:
            cpp.append(emit_jack(j, False)); n += 1
        cpp.append('};')
        # vcotuner's "ramsize" is null in the firmware JSON (the only such
        # case across all 76 circuits) — treat as 0 rather than fail codegen.
        hpp_names.append((name, c["ramsize"] or 0, c["category"] == "deprecated", n))
    cpp.append('')
    cpp.append('const CircuitDef kCircuits[] = {')
    for name, ram, dep, n in hpp_names:
        cpp.append(f'    {{"{name}", {ram}, {"true" if dep else "false"}, '
                   f'kJacks_{name}, {n}}},')
    cpp.append('};')
    cpp.append(f'const unsigned kNumCircuits = {len(hpp_names)};')
    cpp.append('')
    cpp.append('const ControllerDef kControllers[] = {')
    for cname, cc in sorted(fw["controllers"].items()):
        cpp.append(f'    {{"{cname}", {cc["ramsize"]}}},')
    cpp.append('};')
    cpp.append(f'const unsigned kNumControllers = {len(fw["controllers"])};')
    cpp.append(r'''
const CircuitDef* findCircuit(const std::string& name) {
    for (unsigned i = 0; i < kNumCircuits; i++)
        if (name == kCircuits[i].name) return &kCircuits[i];
    return nullptr;
}

const ControllerDef* findController(const std::string& name) {
    for (unsigned i = 0; i < kNumControllers; i++)
        if (name == kControllers[i].name) return &kControllers[i];
    return nullptr;
}

// "input3" -> non-empty all-digit suffix "3". Empty if `s` has no trailing
// digits or is entirely digits (a bare number is never a jack name). idx 0 is
// allowed here; the caller validates against the jack's startAt/count range
// (calibrator's tune0..tune8 is a zero-based array).
static bool digitSuffix(const std::string& s, size_t base, int& idx) {
    if (base == 0 || base >= s.size()) return false;
    for (size_t k = base; k < s.size(); k++)
        if (!isdigit((unsigned char)s[k])) return false;
    idx = std::stoi(s.substr(base));
    return idx >= 0;
}

// Longest base name (full, then short) that is a prefix of `param` with an
// all-digit remainder giving a valid 1-based array index. Longest wins so a
// digit-ending base ("button2") beats a shorter one that is also a prefix
// ("button") -- required for matrixmixer/fadermatrix's button11 … button44 and
// led11 … led44, whose bases themselves end in a digit.
static const JackDef* matchArray(const CircuitDef& c, const std::string& param,
                                 bool useShort, int& arrayIndex) {
    const JackDef* best = nullptr;
    size_t bestLen = 0;
    int bestIdx = 0;
    for (unsigned i = 0; i < c.numJacks; i++) {
        const JackDef& j = c.jacks[i];
        const char* nm = useShort ? j.shortName : j.name;
        if (!nm[0]) continue;
        size_t nl = std::strlen(nm);
        if (param.size() <= nl || param.compare(0, nl, nm) != 0) continue;
        int idx;
        if (!digitSuffix(param, nl, idx)) continue;
        if (idx >= (int)j.startAt && idx < (int)j.startAt + (int)j.count && nl > bestLen) {
            best = &j; bestLen = nl; bestIdx = idx - (int)j.startAt + 1;   // internal 1-based
        }
    }
    if (best) arrayIndex = bestIdx;
    return best;
}

const JackDef* findJack(const CircuitDef& c, const std::string& param, int& arrayIndex,
                        int wantInput) {
    // Direction filter: wantInput -1 = any (loader), 1 = inputs only, 0 =
    // outputs only (Circuit::in()/out()). Needed where one circuit uses the
    // same name for an input and an output (algoquencer: `pitch1..pitch16`
    // inputs vs the `pitch` output).
    auto dirOk = [&](const JackDef& j) {
        return wantInput < 0 || j.isInput == (wantInput == 1);
    };
    // Exact literal match first: scalar jacks whose name/short alias itself
    // ends in a digit (math's "log2"/"l2", ifequal's "input1"/"i1", midiin's
    // "clock8"/"c8"). Scalars beat array bases so a bare name that exists as
    // BOTH a scalar and an array base (algoquencer's `pitch`) resolves to the
    // scalar; the array is still reachable as name1..nameN.
    for (int pass = 0; pass < 2; pass++) {
        for (unsigned i = 0; i < c.numJacks; i++) {
            const JackDef& j = c.jacks[i];
            if (!dirOk(j) || (pass == 0) != (j.count == 1)) continue;
            if (param == j.name) { arrayIndex = 1; return &j; }
        }
        for (unsigned i = 0; i < c.numJacks; i++) {
            const JackDef& j = c.jacks[i];
            if (!dirOk(j) || (pass == 0) != (j.count == 1)) continue;
            if (j.shortName[0] && param == j.shortName) { arrayIndex = 1; return &j; }
        }
    }
    // Array element by longest-prefix match. Full names before short aliases,
    // in case a short alias for one jack collides with the full name of another.
    if (const JackDef* j = matchArray(c, param, /*useShort=*/false, arrayIndex)) { if (dirOk(*j)) return j; }
    if (const JackDef* j = matchArray(c, param, /*useShort=*/true,  arrayIndex)) { if (dirOk(*j)) return j; }
    return nullptr;
}

} // namespace droid::gen''')

    hpp = f'''// GENERATED by tools/jackgen/jackgen.py — DO NOT EDIT
// source firmware: {fw["firmware_version"]}
#pragma once
#include <cstdint>
#include <string>

namespace droid::gen {{

enum class JackType : uint8_t {{ Cv, Gate, Trigger, Fraction, Bipolar, Integer, Stepped, VoltPerOctave, Text }};
enum class RamHint : uint8_t {{ Input, Output, TaptempoInput, TriggerInput, TriggerOutput }};

struct JackDef {{
    const char* name;        // base name; arrays are name1..name<count>
    const char* shortName;   // "" if none
    JackType type;
    RamHint ramHint;
    uint8_t count;           // 1 for scalar jacks
    uint8_t startAt;         // first patch-text index (1 for input1..; calibrator's tune0.. is 0)
    bool isInput;
    bool hasDefault;
    float defaultValue;
}};

struct CircuitDef {{
    const char* name;
    unsigned ramSize;        // base RAM, bytes
    bool deprecated;
    const JackDef* jacks;    // inputs first, then outputs
    unsigned numJacks;
}};

struct ControllerDef {{ const char* name; unsigned ramSize; }};

constexpr unsigned kAvailableMemory[2] = {{{fw["available_memory"]["master16"]}, {fw["available_memory"]["master18"]}}};
constexpr unsigned kInitialJacktableSize = {fw["jacktable_initial_size"]};

extern const CircuitDef kCircuits[];
extern const unsigned kNumCircuits;
extern const ControllerDef kControllers[];
extern const unsigned kNumControllers;

const CircuitDef* findCircuit(const std::string& name);
const ControllerDef* findController(const std::string& name);
// wantInput: -1 = either direction (loader), 1 = inputs only, 0 = outputs only.
const JackDef* findJack(const CircuitDef& c, const std::string& param, int& arrayIndex,
                        int wantInput = -1);

}} // namespace droid::gen
'''
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "jacktables.gen.hpp").write_text(hpp)
    (OUT / "jacktables.gen.cpp").write_text("\n".join(cpp) + "\n")
    print(f"wrote {OUT}/jacktables.gen.{{hpp,cpp}} ({len(hpp_names)} circuits)")


if __name__ == "__main__":
    main()
