#!/usr/bin/env python3
"""Generate engine/gen/scales.gen.cpp from manual/scales.md.

The manual's chapter 15 table lists, for each of the 108 Sinfonion scales (at
root = C), the pitch class of 12 columns: the seven scale degrees
I II III IV V VI VII followed by the five fill notes fill1..fill5. Every row is
a complete permutation of the 12 chromatic pitch classes.

Output: `const int8_t kScales[108][12]`, storing pitch classes 0..11 in the
manual's *column* order [I, II, III, IV, V, VI, VII, fill1..fill5]. The runtime
core (engine/src/notes.cpp) applies pitch ordering and root transposition; this
table is a faithful, mechanical transcription of the manual — lookup only, no
computation.

Deterministic output; the generated file is committed. Rerun with `make gen`
after the manual's scale table changes. Stdlib only (python3)."""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "manual/scales.md"
OUT = ROOT / "engine/gen"

# Note name -> pitch class. The manual uses U+266F (♯); accept ASCII '#' too.
BASE = {"C": 0, "D": 2, "E": 4, "F": 5, "G": 7, "A": 9, "B": 11}


def note_to_pc(cell):
    s = cell.strip()
    if not s or s[0] not in BASE:
        raise ValueError(f"unparsable note {cell!r}")
    pc = BASE[s[0]]
    rest = s[1:]
    if rest in ("♯", "#"):
        pc = (pc + 1) % 12
    elif rest != "":
        raise ValueError(f"unparsable note {cell!r}")
    return pc


def parse_rows(text):
    rows = []
    row_re = re.compile(r"^\|\s*(\d+)\s*\|")
    for line in text.splitlines():
        if not row_re.match(line):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        # cells = [Nr, Scale name, I, II, III, IV, V, VI, VII, fill1..fill5]
        if len(cells) != 14:
            raise ValueError(f"row {cells[0]!r}: expected 14 columns, got {len(cells)}")
        nr = int(cells[0])
        pcs = [note_to_pc(c) for c in cells[2:14]]
        rows.append((nr, pcs))
    return rows


def main():
    if not SRC.exists():
        sys.exit(f"missing {SRC}")
    rows = parse_rows(SRC.read_text(encoding="utf-8"))

    # Validation: exactly 108 rows numbered 0..107 in order; 12 distinct pcs each.
    assert len(rows) == 108, f"expected 108 scales, got {len(rows)}"
    for i, (nr, pcs) in enumerate(rows):
        assert nr == i, f"scale rows out of order: position {i} is numbered {nr}"
        assert len(pcs) == 12, f"scale {nr}: expected 12 notes, got {len(pcs)}"
        assert len(set(pcs)) == 12, f"scale {nr}: pitch classes not distinct: {pcs}"

    lines = [
        "// GENERATED by tools/scalegen/scalegen.py — DO NOT EDIT",
        "// source: manual/scales.md (DROID manual chapter 15, firmware blue-7)",
        '#include "scales.gen.hpp"',
        "",
        "namespace droid::gen {",
        "",
        "// Pitch classes 0..11 at root = C, in column order",
        "// [I, II, III, IV, V, VI, VII, fill1, fill2, fill3, fill4, fill5].",
        f"const int8_t kScales[{len(rows)}][12] = {{",
    ]
    for nr, pcs in rows:
        body = ", ".join(f"{p:2d}" for p in pcs)
        lines.append(f"    {{{body}}},  // {nr}")
    lines.append("};")
    lines.append("")
    lines.append("} // namespace droid::gen")

    hpp = f"""// GENERATED by tools/scalegen/scalegen.py — DO NOT EDIT
// source: manual/scales.md (DROID manual chapter 15, firmware blue-7)
#pragma once
#include <cstdint>

namespace droid::gen {{

constexpr int kNumScales = {len(rows)};
constexpr int kNotesPerScale = 12;

// kScales[degree][column]: pitch class 0..11 (root = C) for the 12 columns
// [I, II, III, IV, V, VI, VII, fill1..fill5]. Column order is the manual's;
// pitch ordering + root transposition happen in engine/src/notes.cpp.
extern const int8_t kScales[{len(rows)}][12];

}} // namespace droid::gen
"""
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "scales.gen.hpp").write_text(hpp)
    (OUT / "scales.gen.cpp").write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}/scales.gen.{{hpp,cpp}} ({len(rows)} scales)")


if __name__ == "__main__":
    main()
