// droidcheck — headless runner for the DROID Forge patch "problem checker".
//
// Reuses the Forge's own parser + Patch::updateProblems() so the results match
// what the GUI shows in its problem panel. GUI-only bits (modules/rackview) are
// not linked; the two ModuleBuilder symbols the checker references are provided
// by modulebuilder_stub.cpp.
//
// Usage: droidcheck [--experimental] [--labels] [--ram] patch1.ini [patch2.ini ...]
// Exit code: number of patches that have at least one problem (0 = all clean).
//
// --labels dumps the register labels the Forge's parser extracted from each
// patch's header comments, one per line:
//
//     LABEL <file> <type> <controller> <g8> <number> |<shorthand>|<text>
//
// This is the parity oracle for the engine's own extractor
// (engine/src/labels.cpp) — `make labelcheck` diffs the two. Nothing else in
// the check output uses the LABEL prefix, so it greps cleanly.
//
// --ram dumps the Forge's own RAM figure for each patch in BOTH deploy modes:
//
//     RAM <file> plain  <bytes>
//     RAM <file> shared <bytes>
//
// "shared" is with the Forge preference "Detect and share duplicate values for
// inputs" (compression/deduplicate_jacks) on, "plain" with it off. This is the
// parity oracle for engine/src/ram.cpp — `make ramcheck` diffs the two
// (issue #88). See the note at the call site for the one correction applied to
// Patch::usedRAM so that both sides measure the same thing.
//
// --experimental allows vcvoid-only EXPERIMENTAL circuits (#12). They are
// merged into the embedded firmware description at build time so the Forge
// model can parse them, but WITHOUT this flag each use is reported as a
// problem — a clean default run must keep meaning "the real Forge would accept
// this patch". With the flag they are validated like any other circuit (jack
// names, duplicate outputs, registers, memory).

#include "patchparser.h"
#include "patch.h"
#include "patchsection.h"
#include "circuit.h"
#include "patchproblem.h"
#include "parseexception.h"
#include "registerlabels.h"
#include "imagecache.h"
#include "droidfirmware.h"
#include "experimental_names.h"   // generated by build.sh from the overlay

#include <QCoreApplication>
#include <QDir>
#include <QFileInfo>
#include <QSettings>
#include <QTextStream>

int main(int argc, char **argv)
{
    QCoreApplication app(argc, argv);
    QCoreApplication::setOrganizationName("droidcheck");
    QCoreApplication::setApplicationName("droidcheck");
    // The Forge reads its deploy preferences through a default-constructed
    // QSettings (patch.cpp toDeployString / updateMemoryProblems). --ram writes
    // those keys, so point QSettings at a scratch ini under the temp directory
    // rather than the real per-user store — a parity run must not leave
    // anything behind on the machine it ran on.
    QSettings::setDefaultFormat(QSettings::IniFormat);
    QSettings::setPath(QSettings::IniFormat, QSettings::UserScope,
                       QDir::tempPath() + "/droidcheck-settings");
    // That store outlives the process, so a previous --ram run would leave
    // deduplicate_jacks on and every later problem check would judge memory as
    // if sharing were enabled. Start each run from the Forge's own defaults.
    QSettings().clear();

    ImageCache imageCache;     // registers the_image_cache
    DroidFirmware firmware;    // registers the_firmware (loads :droidfirmware.json)

    QTextStream out(stdout);
    out << "DROID Forge problem checker  (firmware " << firmware.version() << ")\n";
    out << "======================================================\n";

    int filesWithProblems = 0;
    bool allowExperimental = false;
    bool dumpLabels = false;
    bool dumpRam = false;
    for (int i = 1; i < argc; i++) {
        QString arg = QString::fromLocal8Bit(argv[i]);
        if (arg == "--experimental") allowExperimental = true;
        else if (arg == "--labels")  dumpLabels = true;
        else if (arg == "--ram")     dumpRam = true;
    }
    if (allowExperimental)
        out << "(experimental circuits allowed)\n";

    int filesChecked = 0;
    for (int i = 1; i < argc; i++) {
        QString path = QString::fromLocal8Bit(argv[i]);
        if (path == "--experimental" || path == "--labels" || path == "--ram") continue;
        filesChecked++;
        QString base = QFileInfo(path).fileName();

        Patch patch;
        PatchParser parser;
        try {
            parser.parseFile(path, &patch);
        }
        catch (ParseException &e) {
            out << "\nFAIL  " << base << "\n";
            out << "        parse error: " << e.toString() << "\n";
            filesWithProblems++;
            continue;
        }

        if (dumpLabels) {
            // QMap iterates in key order, so this is deterministic; the
            // comparison script sorts both sides anyway.
            const RegisterLabels &labels = patch.getRegisterLabels();
            for (auto it = labels.constBegin(); it != labels.constEnd(); ++it) {
                const AtomRegister &a = it.key();
                out << "LABEL " << base << " " << QChar(a.getRegisterType()) << " "
                    << a.getController() << " " << a.getG8Number() << " "
                    << a.getNumber() << " |" << it.value().shorthand << "|"
                    << it.value().description << "\n";
            }
        }

        if (dumpRam) {
            for (int shared = 0; shared <= 1; shared++) {
                QSettings settings;
                settings.setValue("compression/deduplicate_jacks", shared == 1);
                // Pinned so the measurement cannot drift with a stray setting;
                // neither affects the RAM figure, only the deployed text.
                settings.setValue("compression/use_shortnames", false);
                settings.setValue("compression/rename_cables", false);
                settings.sync();

                QStringList breakdown;
                unsigned ram = patch.usedRAM(breakdown);
                // Patch::usedRAM charges the X7's RAM only when the patch
                // actually needs one, but Patch::updateMemoryProblems — the
                // rule that decides whether a patch LOADS, and the one
                // engine/src/ram.cpp mirrors — always reserves it on a MASTER.
                // Apply that here so both sides report the same quantity.
                if (patch.typeOfMaster() == 16 && !patch.needsX7())
                    ram += the_firmware->controllerUsedRAM("x7");
                out << "RAM " << base << " " << (shared ? "shared" : "plain")
                    << " " << ram << "\n";
            }
            // Back to the Forge defaults (sharing off) for the problem check
            // below, which must keep meaning what a default Forge reports.
            QSettings settings;
            settings.clear();
            settings.sync();
        }

        patch.updateProblems();
        const QList<PatchProblem *> &problems = patch.allProblems();

        // Experimental circuits are in the embedded firmware (so the patch
        // parses and every other check still runs), but they do not exist on
        // hardware — report each use unless the caller opted in.
        QStringList experimentalUses;
        if (!allowExperimental) {
            for (auto *section : patch.getSections())
                for (auto *circuit : section->getCircuits()) {
                    QString name = circuit->getName();
                    for (const char **e = kExperimentalCircuits; *e; e++)
                        if (name == *e) experimentalUses << name;
                }
        }

        if (problems.isEmpty() && experimentalUses.isEmpty()) {
            out << "\nOK    " << base << "  — no problems\n";
        }
        else {
            filesWithProblems++;
            out << "\nFAIL  " << base << "  — "
                << (problems.count() + experimentalUses.count()) << " problem(s)\n";
            for (const QString &name : experimentalUses)
                out << "        [experimental] Circuit '" << name
                    << "' is experimental (vcvoid only, not available on DROID "
                       "hardware). Pass --experimental to allow it.\n";
            for (auto *p : problems) {
                const CursorPosition &pos = p->getCursorPosition();
                out << "        [section " << p->getSection()
                    << ", circuit " << pos.circuitNr
                    << ", row " << pos.row
                    << ", col " << pos.column << "] "
                    << p->getReason() << "\n";
            }
        }
    }

    out << "\n======================================================\n";
    out << filesChecked << " patch(es) checked, "
        << filesWithProblems << " with problems.\n";
    out.flush();
    return filesWithProblems;
}
