// droidcheck — headless runner for the DROID Forge patch "problem checker".
//
// Reuses the Forge's own parser + Patch::updateProblems() so the results match
// what the GUI shows in its problem panel. GUI-only bits (modules/rackview) are
// not linked; the two ModuleBuilder symbols the checker references are provided
// by modulebuilder_stub.cpp.
//
// Usage: droidcheck [--experimental] [--labels] patch1.ini [patch2.ini ...]
// Exit code: number of patches that have at least one problem (0 = all clean).
//
// --labels dumps the register labels the Forge's parser extracted from each
// patch's header comments, one per line:
//
//     LABEL <file> <type> <controller> <g8> <number> |<shorthand>|<text>
//
// This is the parity oracle for the engine's own extractor
// (engine/src/labels.cpp) — `make labelcheck` diffs the two. Nothing else in
// the check output uses the LABEL prefix, so it greps cleanly.
//
// --experimental allows vcvoid-only EXPERIMENTAL circuits (#12). They are
// merged into the embedded firmware description at build time so the Forge
// model can parse them, but WITHOUT this flag each use is reported as a
// problem — a clean default run must keep meaning "the real Forge would accept
// this patch". With the flag they are validated like any other circuit (jack
// names, duplicate outputs, registers, memory).

#include "patchparser.h"
#include "patch.h"
#include "patchsection.h"
#include "circuit.h"
#include "patchproblem.h"
#include "parseexception.h"
#include "registerlabels.h"
#include "imagecache.h"
#include "droidfirmware.h"
#include "experimental_names.h"   // generated by build.sh from the overlay

#include <QCoreApplication>
#include <QFileInfo>
#include <QTextStream>

int main(int argc, char **argv)
{
    QCoreApplication app(argc, argv);
    QCoreApplication::setOrganizationName("droidcheck");
    QCoreApplication::setApplicationName("droidcheck");

    ImageCache imageCache;     // registers the_image_cache
    DroidFirmware firmware;    // registers the_firmware (loads :droidfirmware.json)

    QTextStream out(stdout);
    out << "DROID Forge problem checker  (firmware " << firmware.version() << ")\n";
    out << "======================================================\n";

    int filesWithProblems = 0;
    bool allowExperimental = false;
    bool dumpLabels = false;
    for (int i = 1; i < argc; i++) {
        QString arg = QString::fromLocal8Bit(argv[i]);
        if (arg == "--experimental") allowExperimental = true;
        else if (arg == "--labels")  dumpLabels = true;
    }
    if (allowExperimental)
        out << "(experimental circuits allowed)\n";

    int filesChecked = 0;
    for (int i = 1; i < argc; i++) {
        QString path = QString::fromLocal8Bit(argv[i]);
        if (path == "--experimental" || path == "--labels") continue;
        filesChecked++;
        QString base = QFileInfo(path).fileName();

        Patch patch;
        PatchParser parser;
        try {
            parser.parseFile(path, &patch);
        }
        catch (ParseException &e) {
            out << "\nFAIL  " << base << "\n";
            out << "        parse error: " << e.toString() << "\n";
            filesWithProblems++;
            continue;
        }

        if (dumpLabels) {
            // QMap iterates in key order, so this is deterministic; the
            // comparison script sorts both sides anyway.
            const RegisterLabels &labels = patch.getRegisterLabels();
            for (auto it = labels.constBegin(); it != labels.constEnd(); ++it) {
                const AtomRegister &a = it.key();
                out << "LABEL " << base << " " << QChar(a.getRegisterType()) << " "
                    << a.getController() << " " << a.getG8Number() << " "
                    << a.getNumber() << " |" << it.value().shorthand << "|"
                    << it.value().description << "\n";
            }
        }

        patch.updateProblems();
        const QList<PatchProblem *> &problems = patch.allProblems();

        // Experimental circuits are in the embedded firmware (so the patch
        // parses and every other check still runs), but they do not exist on
        // hardware — report each use unless the caller opted in.
        QStringList experimentalUses;
        if (!allowExperimental) {
            for (auto *section : patch.getSections())
                for (auto *circuit : section->getCircuits()) {
                    QString name = circuit->getName();
                    for (const char **e = kExperimentalCircuits; *e; e++)
                        if (name == *e) experimentalUses << name;
                }
        }

        if (problems.isEmpty() && experimentalUses.isEmpty()) {
            out << "\nOK    " << base << "  — no problems\n";
        }
        else {
            filesWithProblems++;
            out << "\nFAIL  " << base << "  — "
                << (problems.count() + experimentalUses.count()) << " problem(s)\n";
            for (const QString &name : experimentalUses)
                out << "        [experimental] Circuit '" << name
                    << "' is experimental (vcvoid only, not available on DROID "
                       "hardware). Pass --experimental to allow it.\n";
            for (auto *p : problems) {
                const CursorPosition &pos = p->getCursorPosition();
                out << "        [section " << p->getSection()
                    << ", circuit " << pos.circuitNr
                    << ", row " << pos.row
                    << ", col " << pos.column << "] "
                    << p->getReason() << "\n";
            }
        }
    }

    out << "\n======================================================\n";
    out << filesChecked << " patch(es) checked, "
        << filesWithProblems << " with problems.\n";
    out.flush();
    return filesWithProblems;
}
