#!/usr/bin/env python3
"""Generate/refresh circuits-status.yaml from manual frontmatter.

Preserves human/pipeline edits: existing entries keep status, notes,
depends_on, fable5-reviewed, fable5-reviewer-notes; only new circuits are
added (status: todo). Rank policy:
  master-only first, then controller-enhanced, controller-required, x7-required;
  within a binding: easy < moderate < hard; headless < rack-automated <
  requires-human; alphabetical last. not-feasible -> status not-feasible, no rank.
Circuits are gated by depends_on/blocked, not by deleting entries.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
CIRCUITS = ROOT / "manual/circuits"
LEDGER = ROOT / "circuits-status.yaml"

BINDING_ORDER = {"master-only": 0, "controller-enhanced": 1,
                 "controller-required": 2, "x7-required": 3}
DIFF_ORDER = {"easy": 0, "moderate": 1, "hard": 2}
VERIF_ORDER = {"headless": 0, "rack-automated": 1, "requires-human": 2}

# Circuits that must exist before others make sense, and milestone gates.
# Edit freely; regeneration preserves this via the merge step.
DEFAULT_DEPS = {
    # example: "select" powers overlay circuits; add discovered deps over time
}
MILESTONE_BLOCKS = {
    "controller-required": "blocked: needs controller expander framework (M4)",
    "x7-required": "blocked: needs X7 module (M5)",
}


def parse_frontmatter(path):
    text = path.read_text()
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        return None
    fm = {}
    for line in m.group(1).splitlines():
        mm = re.match(r"^(\w+):\s*(.*)$", line)
        if mm:
            fm[mm.group(1)] = mm.group(2).strip().strip('"')
    return fm


def load_existing():
    """Parse the existing ledger (simple flat schema) into a dict, if present.

    Field values keep their continuation lines verbatim (multi-line quoted
    strings), so preserved fields round-trip unchanged."""
    if not LEDGER.exists():
        return {}
    entries, cur, field = {}, None, None
    for line in LEDGER.read_text().splitlines():
        m = re.match(r"^  ([\w-]+):\s*$", line)
        if m:
            cur, field = m.group(1), None
            entries[cur] = {}
            continue
        m = re.match(r"^    ([\w-]+):\s*(.*)$", line)
        if m and cur:
            field = m.group(1)
            entries[cur][field] = m.group(2)
            continue
        if cur and field and re.match(r"^      +\S", line):
            entries[cur][field] += "\n" + line
    return entries


def main():
    existing = load_existing()
    rows = []
    for f in sorted(CIRCUITS.glob("*.md")):
        if f.name == "index.md":
            continue
        fm = parse_frontmatter(f)
        if not fm or "circuit" not in fm:
            sys.exit(f"bad frontmatter in {f}")
        rows.append(fm)

    ranked = []
    for fm in rows:
        name = fm["circuit"]
        diff = fm.get("impl_difficulty", "hard")
        if diff == "not-feasible":
            continue
        key = (BINDING_ORDER.get(fm.get("controller_binding"), 9),
               DIFF_ORDER.get(diff, 9),
               VERIF_ORDER.get(fm.get("verification"), 9),
               name)
        ranked.append((key, fm))
    ranked.sort(key=lambda kv: kv[0])
    rank_of = {fm["circuit"]: (i + 1) * 10 for i, (_, fm) in enumerate(ranked)}

    out = ["# GENERATED by tools/ledger/genledger.py — status/notes/depends_on",
           "# fields are preserved across",
           "# regeneration; everything else refreshes from the manual.",
           "circuits:"]
    for fm in rows:
        name = fm["circuit"]
        diff = fm.get("impl_difficulty", "hard")
        old = existing.get(name, {})
        if diff == "not-feasible":
            status = "not-feasible"
        else:
            status = old.get("status", "todo")
        notes = old.get("notes", '""')
        if status == "todo" and not old:
            gate = MILESTONE_BLOCKS.get(fm.get("controller_binding"))
            if gate:
                status = "blocked"
                notes = f'"{gate.split(": ", 1)[1]}"'
        out.append(f"  {name}:")
        out.append(f"    status: {status}")
        out.append(f"    difficulty: {diff}")
        out.append(f"    binding: {fm.get('controller_binding', 'unknown')}")
        if diff != "not-feasible":
            out.append(f"    verification: {fm.get('verification', 'unknown')}")
            out.append(f"    spec_gap: {fm.get('spec_gap', 'false')}")
            out.append(f"    rank: {rank_of.get(name, 9999)}")
        out.append(f"    depends_on: {old.get('depends_on', '[]')}")
        out.append(f"    notes: {notes}")
    LEDGER.write_text("\n".join(out) + "\n")
    print(f"wrote {LEDGER} ({len(rows)} circuits)")


if __name__ == "__main__":
    main()
